# Global settings
source global-config.conf

# Board-specific
BOARD=rpi4b

# Kernel
#BRANCH=legacy
#BRANCH=current
BRANCH=edge

ENABLE_EXTENSIONS="$ENABLE_EXTENSIONS,mpwrd-rpi-customize,nymea-networkmanager"
