name: Build Armbian with Userpatches

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    # Use ubuntu-24.04 for x86_64 builds, ubuntu-24.04-arm for ARM builds (everything else)
    runs-on: ${{ contains(matrix.config, 'x86_64') && 'ubuntu-24.04' || 'ubuntu-24.04-arm' }}
    strategy:
      matrix:
        include:
          - config: ebyte-ecb41-pge
            armbian_ref: v26.05 # Stable Branch
          - config: forlinx-ok3506-s12
            armbian_ref: v26.05 # Stable Branch
          - config: luckfox-lyra-plus
            armbian_ref: v26.05 # Stable Branch
          - config: luckfox-lyra-ultra-w
            armbian_ref: v26.05 # Stable Branch
          - config: luckfox-lyra-zero-w
            armbian_ref: v26.05 # Stable Branch
          - config: luckfox-pico-max
            armbian_ref: v26.05 # Stable Branch
          - config: luckfox-pico-mini
            armbian_ref: v26.05 # Stable Branch
          - config: raspberry-pi-64bit
            armbian_ref: v26.05 # Stable Branch
          - config: uefi-x86_64
            armbian_ref: v26.05 # Stable Branch
      fail-fast: false
    steps:
      - name: Checkout armbian/build into workspace root
        uses: actions/checkout@v6
        with:
          repository: armbian/build
          ref: ${{ matrix.armbian_ref }}

      - name: Checkout current repository into userpatches
        uses: actions/checkout@v6
        with:
          path: userpatches

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Compile ${{ matrix.config }} image
        shell: bash
        run: >
          ./compile.sh build ${{ matrix.config }}
          PREFER_DOCKER=yes
          KERNEL_CONFIGURE=no
          SHARE_LOGS=no

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.config }}
          path: output/images/*
