name: Release mPWRD-OS

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    # reuse workflow from build-armbian.yaml
    uses: ./.github/workflows/build-armbian.yaml

  release:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - name: Get Version
        id: version
        run: echo "mpwrd=$(cat mPWRD-VERSION)" >> $GITHUB_OUTPUT

      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true
          path: output/images/

      - name: List Downloaded Artifacts
        run: ls -lah output/images/

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          files: output/images/*.img.xz
          draft: true
          prerelease: true
          name: mPWRD-OS ${{ steps.version.outputs.mpwrd }} Alpha
          tag_name: v${{ steps.version.outputs.mpwrd }}
